# For more information: https://github.com/julien-r44/adonis-sail
services:
  pgsql:
    image: 'postgres:15'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-default}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-default}', '-U', '${DB_USER}']
      retries: 3
      timeout: 5s
  adonis_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - server-images:/home/node/app/public
    depends_on:
      - pgsql
    command: 'node ace serve --watch'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
  server-images:
