# For more information: https://github.com/julien-r44/adonis-sail
name: minecraft-stats
services:
  pgsql:
    image: 'postgres:15'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-default}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-default}', '-U', '${DB_USER}']
      retries: 3
      timeout: 5s

  adonis_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - server-images:/home/node/app/public
      - /home/node/app/node_modules
    depends_on:
      - pgsql
    command: >
      sh -c "node ace migration:run && npm run build && npm run start"
    networks:
      - sail

  adonis_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - pgsql
      - adonis_app
    command: 'node ace scheduler:run'
    networks:
      - sail
    volumes:
      - ./:/home/node/app
      - server-images:/home/node/app/public
      - /home/node/app/node_modules

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
  server-images:
